environment:
    matrix:
    # node.js
    - nodejs_version: "22"
    - nodejs_version: "24"

platform:
    - x86
    - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - npm run test-ci

build_script:
  - npm run ci